### ISSUE TITLE
对于katex渲染的问题

### ISSUE THREAD

**Issue by singledoggy** [iamcco/markdown-preview.nvim#114]
您的插件非常好用，但是katex对数学公式的渲染依旧有问题，您有同类的插件推荐或者解决方案可以推荐给我吗，对您非常感谢。

**Comment by singledoggy** [comment]
例如在我的博客常常使用的align等等

**Comment by iamcco** [comment]
啥问题？在这里试试 https://katex.org/#demo

**Comment by RyanGreenup** [comment]
KaTeX only supports a subset of what LaTeX does, MathJax implements just about everything but is not commonly used in Markdown applications.

KaTeX will do everything except for numbering equations, in order to align equations you need to use the following format:

$$\begin{aligned}
4x&= 2 \\
 \implies  x&= 2
\end{aligned}$$ 

This is a better way to do it because when using pure LaTeX the `align` environment is a stand alone environment whereas `aligned` expects to be inside an equation environment, this can prevent problems during `pandoc` export.

If you need more LaTeX but don't want to have to fight `pandoc` to get it into HTML I would also suggest looking at `org`-mode with *Spacemacs*

---
*Google* Translate
---


KaTeX仅支持LaTeX的一部分，MathJax几乎可以实现所有功能，但在Markdown应用程序中并不常用。

KaTeX将执行除编号方程式以外的所有操作，为了对齐方程式，您需要使用以下格式：

$$ \ begin {aligned}
4x＆= 2 \\
 \implies x＆= 2
\ end {aligned} $$

这是一种更好的方法，因为在使用纯LaTeX时，“ align”环境是一个独立的环境，而“ aligned”期望在方程式环境中，这可以防止在“ pandoc”导出过程中出现问题。

如果您需要更多的LaTeX但又不想与`pandoc`争用到HTML中，我还建议您使用* Spacemacs *查看`org`模式
