### ISSUE TITLE
Github Flavoured Markdown

### ISSUE THREAD

**Issue by jsycdut** [iamcco/markdown-preview.nvim#17]
Seems this project doesn't support Github Flavoured Makdown,  how about adding Github Flavoured Markdown support?:satisfied:

**Comment by iamcco** [comment]
> Seems this project doesn't support Github Flavoured Makdown, how about adding Github Flavoured Markdown support?😆

The markdown parser it use [markdown-it](https://github.com/markdown-it/markdown-it) which 100% CommonMark support since Github Flavoured Makdown is base on CommonMark. and you can config parser render by setting `mkit` option.

```viml
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ }
```

about options: 
https://github.com/markdown-it/markdown-it/blob/master/README.md#init-with-presets-and-options

and if you still missing something PR is alway welcome.

**Comment by jsycdut** [comment]
That's pretty, many thanks

**Comment by jsycdut** [comment]
> > Seems this project doesn't support Github Flavoured Makdown, how about adding Github Flavoured Markdown support?laughing
> 
> The markdown parser it use [markdown-it](https://github.com/markdown-it/markdown-it) which 100% CommonMark support since Github Flavoured Makdown is base on CommonMark. and you can config parser render by setting `mkit` option.
> 
> ```viml
> let g:mkdp_preview_options = {
>     \ 'mkit': {},
>     \ }
> ```
> 
> about options:
> https://github.com/markdown-it/markdown-it/blob/master/README.md#init-with-presets-and-options
> 
> and if you still missing something PR is alway welcome.

That's pretty, many thanks
