### ISSUE TITLE
E492: Not an editor command: MarkdownPreview

### ISSUE THREAD

**Issue by ahmedselim2017** [iamcco/markdown-preview.nvim#94]
I can't preview my markdown files

[My vim config](https://github.com/ahmedselim2017/dotfiles-scripts/tree/master/dotfiles/nvim) 

nvim --version:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
:checkhealth :
```

health#coc#check
========================================================================
  - OK: Environment check passed
  - WARNING: pyx command not work, some extensions may fail to work, checkout ":help |pythonx|"
  - OK: Javascript bundle found
  - OK: Service started

health#mkdp#check
========================================================================
  - INFO: Platform: linux
  - INFO: Nvim Version: NVIM v0.4.2
  - INFO: Pre build: /home/tozkoparan/.vim/plugged/markdown-preview.nvim/app/bin/markdown-preview-linux
  - INFO: Pre build version: 0.0.9
  - OK: Using pre build

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='rxvt'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          /usr/bin/python3 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python3.7 does not have the "neovim" module. :help |provider-python|
          python3.6 not found in search path or not executable.
          python3.5 not found in search path or not executable.
          python3.4 not found in search path or not executable.
          python3.3 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v10.16.3
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

```

**Comment by iamcco** [comment]
`MarkdownPreview` command is only available for markdown buffer by default.

**Comment by ahmedselim2017** [comment]
It doesn't work on markdown buffers too

**Comment by iamcco** [comment]
Can't not reproduce, it seems something wrong with your neovim.

**Comment by iamcco** [comment]
add log after this line https://github.com/iamcco/markdown-preview.nvim/blob/master/plugin/mkdp.vim#L102 to see what happen when open markdown buffer.

**Comment by ahmedselim2017** [comment]
I think i have solved the issue. It was because of [these](https://github.com/ahmedselim2017/dotfiles-scripts/blob/47b3ec23d64b6c48e8bcc535f501bc0141f9d4f5/dotfiles/nvim/plugins.vim#L144-L156) lines in my config file. Deleting them solved the issue.

**Comment by tapyu** [comment]
I have the same issue on my machine. I don't think that the error is in @ahmedselim2017 's neovim, there is probably some bug in this plugin. Let me put it across:

In my case, I am using a full-lua configuration, which can be found [here](https://github.com/tapyu/dotfiles/tree/main/nvim/.config/nvim) (ignore `init.vim`, it is old and not used anymore). For package manager, I am using [packer](https://github.com/wbthomason/packer.nvim), and I call this plugin in the [following command line](https://github.com/tapyu/dotfiles/blob/4b67cf2b1efc845b29566b6a83784e3a4c720894/nvim/.config/nvim/lua/user/plugins.lua#L62):
```lua
use {'iamcco/markdown-preview.nvim', run = 'cd app && yarn install', cmd = 'MarkdownPreview'}
```

This command is suggested in the own [packer README.md](https://github.com/wbthomason/packer.nvim#:~:text=%2D%2D%20Plugins%20can%20have%20post%2Dinstall/update%20hooks%0A%20%20use%20%7B%27iamcco/markdown%2Dpreview.nvim%27%2C%20run%20%3D%20%27cd%20app%20%26%26%20yarn%20install%27%2C%20cmd%20%3D%20%27MarkdownPreview%27%7D). I've tested the run command and it worked properly.

1. When I run 'MarkdownPreview' in a fresh-opened `.md` file at the very first time, I get the following output
![Screenshot from 2022-04-15 17-20-54](https://user-images.githubusercontent.com/22801918/163628481-3522da1f-2320-4a16-84ae-55be1d66e738.png)
1. I run `PackerStatus`, which prompts
![Screenshot from 2022-04-15 17-20-11](https://user-images.githubusercontent.com/22801918/163628448-50b1b126-9e80-493c-9961-891bda8bbcff.png)
1. I run 'MarkdownPreview' again and it works.

I am not a nvim expert, but it seems pretty odd. I highly suggest replicate this bug with the lua config provided in my repo in order to reach a reliable reproduction of this error. I hope I could help in some way....

**Comment by tapyu** [comment]
I just have found the problem, actually the command should be

```
use {'iamcco/markdown-preview.nvim', run = 'cd app && yarn install'}
```

Even though, I couldn't understand what was the problem in loading the plugin only when I call `:MarkdownPreview`...

**Comment by zim0369** [comment]
Yes, it's hard to reproduce this bug but I experience it frequently.

**Comment by dimaportenko** [comment]
> I just have found the problem, actually the command should be
> 
> ```
> use {'iamcco/markdown-preview.nvim', run = 'cd app && yarn install'}
> ```
> 
> Even though, I couldn't understand what was the problem in loading the plugin only when I call `:MarkdownPreview`...

works for me, thanks!

**Comment by marciomazza** [comment]
I still experience this bug, and trying to open at least 2 markdown files temporarily resolved it
( as previously mentioned by @evccyr ).

Perhaps this issue should be reopened.

**Comment by Yrd980** [comment]
latest i found that this issue commonly because of vim.fn  cann't recognize and yarn cann't detect (my environment is arch linux yarn latest update is 2024-07-11 extra repo and interesting fish is also a bug since its compatibility), i solve it by change second method to npm install
